'use strict';

var mongoose = require('bluebird').promisifyAll(require('mongoose'));

var VolunteerSchema = new mongoose.Schema({
  '': String,
  'Coach E-mail': String,
  'Coach name': String,
  'Division': Number,
  'E-mail': String,
  'First name': String,
  'I will attend training at': String,
  'Job Preference #1': String,
  'Job Preference #2': String,
  'Last name': String,
  'Lunch preference': String,
  'M.name': String,
  'M.region':  String,
  'Membership#': Number,
  'Problem': Number,
  'Region':  String,
  'T-shirt':  String,
  'assoc':  String,
  'assoc_exp': Number,
  'certNbr': Number,
  'cert_p1':  String,
  'cert_p2':  String,
  'cert_p3':  String,
  'cert_p4':  String,
  'cert_p5':  String,
  'cert_score':  String,
  'cert_spont':  String,
  'child_team':  String,
  'city':  String,
  'coach_exp': Number,
  'comment':  String,
  'country':  String,
  'current': String,
  'fax':  String,
  'job_comment':  String,
  'member_exp': Number,
  'modify_on':  String,
  'password':  String,
  'phone': String,
  'position_helds':  String,
  'state':  String,
  'street1':  String,
  'street2':  String,
  'submitdate':  String,
  'username':  String,
  'workphone':  String,
  'zip': Number
});

export default mongoose.model('Volunteer', VolunteerSchema);
